language: java
jdk:
  - oraclejdk11
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
branches:
  only:
    - trunk
dist: trusty
notification:
  email:
    recipients:
      felipealvarez23@outlook.com
script:
  # other script steps might be done before running the actual analysis
  - ./gradlew clean build jacocoMergedReport
