server:
  port: 8080
spring:
  application:
    name: "medida_de_proteccion_backend"
  profiles:
    include: null
    active: "dev-local"

---
server:
  port: 8080
spring:
  application:
    name: "medida_de_proteccion_backend"
  config:
    activate:
      on-profile: dev-local
app:
  allowedOrigins: http://localhost:4200
db:
  schema: "pm_schema"
  password: ""
  dbname: "protection_measure_db"
  port: "5432"
  host: "localhost"
  username: "postgres"

---
spring:
  config:
    activate:
      on-profile: pdn
server:
  port: 8080
app:
  allowedOrigins: http://localhost:4200
db:
  schema: "pm_schema"
  secret:
    region: "us-east-1"
    name: "aws/secretmanager/medida-de-proteccion"
    url: jdbc:postgresql://%s:%s/%s?currentSchema=pm_schema