server:
  port: 8080
spring:
  application:
    name: "medida_de_proteccion_backend"
  profiles:
    include: null
    active: "dev-local"

---
spring:
  config:
    activate:
      on-profile: dev-local
server:
  port: 8080
app:
  allowedOrigins: "http://localhost:4200"
db:
  schema: "pm_schema"
  password: "Delta231092#!."
  dbname: "protection_measure_db"
  port: "5432"
  host: "localhost"
  username: "postgres"

---
spring:
  config:
    activate:
      on-profile: pnd
server:
  port: 8080
app:
  allowedOrigins: "localhost:4200"
db:
  schema: "pm_schema"
  secret:
    region: "us-east-1"
    name: "aws/secret-manager/medida-de-proteccion"