server:
  port: 80
spring:
  application:
    name: "medida_de_proteccion_backend"
  profiles:
    include: null
    active: "dev-local"

---
spring:
  config:
    activate:
      on-profile: dev-local

server:
  port: 80
app:
  allowedOrigins: "localhost:4200"
db:
  schema: "pm_schema"
  password: ""
  dbname: "protection_measure_db"
  port: "5432"
  host: "localhost"
  username: "postgres"

---
spring:
  config:
    activate:
      on-profile: pnd

server:
  port: 80
app:
  allowedOrigins: "localhost:4200"
db:
  schema: "pm_schema"
  secret:
    region: "us-east-1"
    name: "aws/secret-manager/medida-de-proteccion"
    url: jdbc:postgresql://%s:%s/%s?currentSchema=protection_measure_schema